In [2]:
# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Visualización
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# Evaluar linealidad de las relaciones entre las variables
# y la distribución de las variables
# ------------------------------------------------------------------------------
import scipy.stats as stats

# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

# Gestión de los warnings
# -----------------------------------------------------------------------
import warnings
warnings.filterwarnings("ignore")

In [3]:
# Imputación de nulos usando métodos avanzados estadísticos
# -----------------------------------------------------------------------
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

# Librerías de visualización
# -----------------------------------------------------------------------
import seaborn as sns
import matplotlib.pyplot as plt
# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [5]:
df1 = pd.read_csv('Customer Loyalty History.csv')
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Loyalty Number      16737 non-null  int64  
 1   Country             16737 non-null  object 
 2   Province            16737 non-null  object 
 3   City                16737 non-null  object 
 4   Postal Code         16737 non-null  object 
 5   Gender              16737 non-null  object 
 6   Education           16737 non-null  object 
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  object 
 9   Loyalty Card        16737 non-null  object 
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  object 
 12  Enrollment Year     16737 non-null  int64  
 13  Enrollment Month    16737 non-null  int64  
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: f

In [6]:
df2 = pd.read_csv('Customer Flight Activity.csv', )
df2.head(10)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405624 entries, 0 to 405623
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   Loyalty Number               405624 non-null  int64  
 1   Year                         405624 non-null  int64  
 2   Month                        405624 non-null  int64  
 3   Flights Booked               405624 non-null  int64  
 4   Flights with Companions      405624 non-null  int64  
 5   Total Flights                405624 non-null  int64  
 6   Distance                     405624 non-null  int64  
 7   Points Accumulated           405624 non-null  float64
 8   Points Redeemed              405624 non-null  int64  
 9   Dollar Cost Points Redeemed  405624 non-null  int64  
dtypes: float64(1), int64(9)
memory usage: 30.9 MB


In [7]:

df3 = pd.merge(df1, df2, on='Loyalty Number')

# Guarda el resultado en un nuevo archivo CSV
df3.to_csv('archivo_combinado.csv')



In [8]:
df_nulos = pd.DataFrame((df3.isnull().sum() / df3.shape[0]) * 100, columns = ["%_nulos"])

# filtramos el DataFrame para quedarnos solo con aquellas columnas que tengan nulos
df_nulos[df_nulos["%_nulos"] > 0]

%_nulos
Salary              25.312112
Cancellation Year   87.657535
Cancellation Month  87.657535

In [9]:
df3.drop("Cancellation Year", axis=1, inplace = True)

In [10]:
df3.drop("Cancellation Month", axis=1, inplace = True)

In [11]:
df3["Salary"].unique()

array([ 83236.,     nan, 103495., ...,  76178.,  91970., -57297.])

In [12]:
df3.isnull().sum()

Loyalty Number                      0
Country                             0
Province                            0
City                                0
Postal Code                         0
Gender                              0
Education                           0
Salary                         102672
Marital Status                      0
Loyalty Card                        0
CLV                                 0
Enrollment Type                     0
Enrollment Year                     0
Enrollment Month                    0
Year                                0
Month                               0
Flights Booked                      0
Flights with Companions             0
Total Flights                       0
Distance                            0
Points Accumulated                  0
Points Redeemed                     0
Dollar Cost Points Redeemed         0
dtype: int64

In [13]:
df3.isnull().sum()

Loyalty Number                      0
Country                             0
Province                            0
City                                0
Postal Code                         0
Gender                              0
Education                           0
Salary                         102672
Marital Status                      0
Loyalty Card                        0
CLV                                 0
Enrollment Type                     0
Enrollment Year                     0
Enrollment Month                    0
Year                                0
Month                               0
Flights Booked                      0
Flights with Companions             0
Total Flights                       0
Distance                            0
Points Accumulated                  0
Points Redeemed                     0
Dollar Cost Points Redeemed         0
dtype: int64

In [14]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 405624 entries, 0 to 405623
Data columns (total 23 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   Loyalty Number               405624 non-null  int64  
 1   Country                      405624 non-null  object 
 2   Province                     405624 non-null  object 
 3   City                         405624 non-null  object 
 4   Postal Code                  405624 non-null  object 
 5   Gender                       405624 non-null  object 
 6   Education                    405624 non-null  object 
 7   Salary                       302952 non-null  float64
 8   Marital Status               405624 non-null  object 
 9   Loyalty Card                 405624 non-null  object 
 10  CLV                          405624 non-null  float64
 11  Enrollment Type              405624 non-null  object 
 12  Enrollment Year              405624 non-null  int64  
 13 

In [15]:
def convertir(df3):

    
    # Itera sobre las columnas y si son de tipo 'object' (strings), las convierte a minúsculas y reemplaza espacios por '_'
    for columna in df3.columns:
        if df3[columna].dtype == 'object':  # Verifica si la columna es de tipo 'object' (cadena)
            df3[columna] = df3[columna].str.lower().str.replace(' ', '_')
    
    return df3

In [16]:
df3.columns = df3.columns.str.lower().str.replace(' ', '_')

In [17]:
df3["clv"].unique()

array([ 3839.14,  3839.61,  3839.75, ..., 44771.3 , 50568.26, 61134.68])

In [18]:
df3.rename(columns={"clv": "customer_lifetime_value"}, inplace=True)

In [19]:
df3['salary']=df3['salary'].replace(np.nan, "desconocido")

In [20]:
df3.rename(columns={"year": "flying_year"}, inplace=True)

In [21]:
df3.rename(columns={"month": "flying_month"}, inplace=True)

In [22]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 405624 entries, 0 to 405623
Data columns (total 23 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   loyalty_number               405624 non-null  int64  
 1   country                      405624 non-null  object 
 2   province                     405624 non-null  object 
 3   city                         405624 non-null  object 
 4   postal_code                  405624 non-null  object 
 5   gender                       405624 non-null  object 
 6   education                    405624 non-null  object 
 7   salary                       405624 non-null  object 
 8   marital_status               405624 non-null  object 
 9   loyalty_card                 405624 non-null  object 
 10  customer_lifetime_value      405624 non-null  float64
 11  enrollment_type              405624 non-null  object 
 12  enrollment_year              405624 non-null  int64  
 13 

In [23]:
df3["salary"].unique()

array([83236.0, 'desconocido', 103495.0, ..., 76178.0, 91970.0, -57297.0],
      dtype=object)

In [24]:
# Función para convertir valores negativos a positivos
def convertir_a_positivo(valor):
    if isinstance(valor, (int, float)) and valor < 0:
        return abs(valor)
    return valor

# Aplicar la función a la columna específica del DataFrame
df3['salary'] = df3['salary'].apply(convertir_a_positivo)



In [25]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 405624 entries, 0 to 405623
Data columns (total 23 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   loyalty_number               405624 non-null  int64  
 1   country                      405624 non-null  object 
 2   province                     405624 non-null  object 
 3   city                         405624 non-null  object 
 4   postal_code                  405624 non-null  object 
 5   gender                       405624 non-null  object 
 6   education                    405624 non-null  object 
 7   salary                       405624 non-null  object 
 8   marital_status               405624 non-null  object 
 9   loyalty_card                 405624 non-null  object 
 10  customer_lifetime_value      405624 non-null  float64
 11  enrollment_type              405624 non-null  object 
 12  enrollment_year              405624 non-null  int64  
 13 

In [26]:
df3.to_csv("datos_vuelos.csv")